#!/bin/bash

ROOT_DIR=/workspace
RESULTSDIR=$ROOT_DIR/results/misc-checks
OUTFILE=$RESULTSDIR/out
FAILFILE=$RESULTSDIR/fail

if ! stat $RESULTSDIR; then
  exit 0
fi

go get github.com/openconfig/models-ci/validators/misc-checks/...

# all-non-empty-files.txt
find $_MODEL_ROOT -name '*.yang' > $RESULTSDIR/all-non-empty-files.txt 2>> $OUTFILE

# pr-file-parse-log
# This output is used to check for both the version update as well as build
# reachability. The latter requirement requires the script to be generated by
# cmd_gen in a per-model manner.
# TODO(wenbli): Ideally we should do the version and reachability checks
# separately -- i.e. the version script should be fed all of the files; and a
# separate script lists the files that are reachable.
# This requires the check logic within post_results to be changed.
# I'm delaying this because it remains to be seen whether goyang can be
# refactored so we don't need do this inter-process communication via files.
if bash $RESULTSDIR/script.sh >> $OUTFILE 2>> $FAILFILE; then
  # Delete fail file if it's empty and the script passed.
  find $FAILFILE -size 0 -delete
fi
cat $RESULTSDIR/*.pr-file-parse-log > $RESULTSDIR/pr-file-parse-log 2>> $OUTFILE

# changed-files.txt
REPODIR=$RESULTSDIR/base_repo
git clone "git@github.com:$_REPO_SLUG.git" $REPODIR
cd $REPODIR
PRBRANCH=gcb-ci-remote-repo-long-name-to-avoid-conflict
# fetching the PR directly from GitHub handles both normal PRs as well as forks.
git fetch origin pull/$_PR_NUMBER/head:$PRBRANCH
git checkout $PRBRANCH
BASE_COMMIT=$(git merge-base $PRBRANCH origin/master)
git diff --name-only $BASE_COMMIT | grep -E '.*\.yang$' > $RESULTSDIR/changed-files.txt 2>> $OUTFILE

# master-file-parse-log
git checkout $BASE_COMMIT &>> $OUTFILE
if find $REPODIR -name '*.yang' | xargs $GOPATH/bin/ocversion -p $REPODIR > $RESULTSDIR/master-file-parse-log 2>> $FAILFILE; then
  # Delete fail file if it's empty and the script passed.
  find $FAILFILE -size 0 -delete
fi

$GOPATH/bin/post_results -validator=misc-checks -modelRoot=$_MODEL_ROOT -repo-slug=$_REPO_SLUG -pr-number=$_PR_NUMBER -commit-sha=$COMMIT_SHA -branch=$BRANCH_NAME
BADGEFILE=$RESULTSDIR/upload-badge.sh
if stat $BADGEFILE; then
  bash $BADGEFILE
fi
